# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/buser/c_projects/RTOS

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/buser/c_projects/RTOS

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/buser/c_projects/RTOS/CMakeFiles /home/buser/c_projects/RTOS//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/buser/c_projects/RTOS/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rtos

# Build rule for target.
rtos: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rtos
.PHONY : rtos

# fast build rule for target.
rtos/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtos.dir/build.make CMakeFiles/rtos.dir/build
.PHONY : rtos/fast

core/scheduler/Src/scheduler.o: core/scheduler/Src/scheduler.c.o
.PHONY : core/scheduler/Src/scheduler.o

# target to build an object file
core/scheduler/Src/scheduler.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtos.dir/build.make CMakeFiles/rtos.dir/core/scheduler/Src/scheduler.c.o
.PHONY : core/scheduler/Src/scheduler.c.o

core/scheduler/Src/scheduler.i: core/scheduler/Src/scheduler.c.i
.PHONY : core/scheduler/Src/scheduler.i

# target to preprocess a source file
core/scheduler/Src/scheduler.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtos.dir/build.make CMakeFiles/rtos.dir/core/scheduler/Src/scheduler.c.i
.PHONY : core/scheduler/Src/scheduler.c.i

core/scheduler/Src/scheduler.s: core/scheduler/Src/scheduler.c.s
.PHONY : core/scheduler/Src/scheduler.s

# target to generate assembly for a file
core/scheduler/Src/scheduler.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtos.dir/build.make CMakeFiles/rtos.dir/core/scheduler/Src/scheduler.c.s
.PHONY : core/scheduler/Src/scheduler.c.s

core/task/Src/queue/queue.o: core/task/Src/queue/queue.c.o
.PHONY : core/task/Src/queue/queue.o

# target to build an object file
core/task/Src/queue/queue.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtos.dir/build.make CMakeFiles/rtos.dir/core/task/Src/queue/queue.c.o
.PHONY : core/task/Src/queue/queue.c.o

core/task/Src/queue/queue.i: core/task/Src/queue/queue.c.i
.PHONY : core/task/Src/queue/queue.i

# target to preprocess a source file
core/task/Src/queue/queue.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtos.dir/build.make CMakeFiles/rtos.dir/core/task/Src/queue/queue.c.i
.PHONY : core/task/Src/queue/queue.c.i

core/task/Src/queue/queue.s: core/task/Src/queue/queue.c.s
.PHONY : core/task/Src/queue/queue.s

# target to generate assembly for a file
core/task/Src/queue/queue.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtos.dir/build.make CMakeFiles/rtos.dir/core/task/Src/queue/queue.c.s
.PHONY : core/task/Src/queue/queue.c.s

core/task/Src/task.o: core/task/Src/task.c.o
.PHONY : core/task/Src/task.o

# target to build an object file
core/task/Src/task.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtos.dir/build.make CMakeFiles/rtos.dir/core/task/Src/task.c.o
.PHONY : core/task/Src/task.c.o

core/task/Src/task.i: core/task/Src/task.c.i
.PHONY : core/task/Src/task.i

# target to preprocess a source file
core/task/Src/task.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtos.dir/build.make CMakeFiles/rtos.dir/core/task/Src/task.c.i
.PHONY : core/task/Src/task.c.i

core/task/Src/task.s: core/task/Src/task.c.s
.PHONY : core/task/Src/task.s

# target to generate assembly for a file
core/task/Src/task.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtos.dir/build.make CMakeFiles/rtos.dir/core/task/Src/task.c.s
.PHONY : core/task/Src/task.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtos.dir/build.make CMakeFiles/rtos.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtos.dir/build.make CMakeFiles/rtos.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtos.dir/build.make CMakeFiles/rtos.dir/main.c.s
.PHONY : main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... rtos"
	@echo "... core/scheduler/Src/scheduler.o"
	@echo "... core/scheduler/Src/scheduler.i"
	@echo "... core/scheduler/Src/scheduler.s"
	@echo "... core/task/Src/queue/queue.o"
	@echo "... core/task/Src/queue/queue.i"
	@echo "... core/task/Src/queue/queue.s"
	@echo "... core/task/Src/task.o"
	@echo "... core/task/Src/task.i"
	@echo "... core/task/Src/task.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

